/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Int,
});
export const TransactionStatus = IDL.Variant({
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'topup' : IDL.Null,
  'send' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'from' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMoney' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'topUp' : IDL.Func([IDL.Int], [], []),
  'userExists' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Int,
  });
  const TransactionStatus = IDL.Variant({
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'topup' : IDL.Null,
    'send' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'from' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMoney' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'topUp' : IDL.Func([IDL.Int], [], []),
    'userExists' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };